---
# tasks file for joe-speedboat.elastic_easy/tasks/main.yml
- name: configure bootstrap.memory_lock
  include_tasks: bootstrap_memory_lock.yml
- name: create cluster configuration
  block:
  - name: find hosts with ee_is_master=true in hostvars of inventory
    set_fact:
      ee_masters: "{{ ee_masters|default(['']) + [ hostvars[item]['inventory_hostname_short'] ]}}"
    with_items: "{{ ansible_play_hosts_all }}"
    when: "hostvars[item]['ee_is_master']|default('true')|bool is true"
  - name: format masters list into dict ee_config_masters_list
    set_fact:
      ee_config_masters_list:
        cluster.initial_master_nodes: "{{ ee_masters|select()|list|unique|join(',') }}"
        discovery.seed_hosts: "{{ ee_masters|select()|list|join(',') }}"
  - name: merge ee_config_template_cluster -over-> ee_config_template_all -into-> es_config 
    set_fact:
      es_config: "{{ ee_config_template_all|combine(ee_config_template_cluster) }}"
  - name: inject ee_masters into es_config if not defined anywhere
    set_fact:
      es_config: "{{ es_config|combine(ee_config_masters_list) }}"
    when: ee_master_nodes == ''
  when: ansible_play_hosts_all|length > 1
- name: create single node configuration
  block:
  - name: merge ee_config_template_single -over-> ee_config_template_all -into-> es_config
    set_fact:
      es_config: "{{ ee_config_template_all|combine(ee_config_template_single) }}"
  when: (ansible_play_hosts_all|length) == 1
- name: merge ee_config over es_config
  set_fact:
    es_config: "{{ es_config|combine(ee_config)}}"

- name: run role elastic.elasticsearch role
  include_role:
    name: elastic.elasticsearch
...

